config/routes.rb
Rails.application.routes.draw do
 
  resources :favorite_articles
  # resources :read_later_articles
 
  root 'sessions#new'
  get 'news_map', to: 'home#map', as: "home_map"
  get 'home', to: 'home#index', as: "home"

  resources :articles

 post '/articles/article_save', to: 'articles#article_save'

 get '/countries/:slug_name', to: "countries#show", as: "country_articles"
 get '/today', to: "countries#index"

 # get '/countries/json', to: "map#countries"

 get '/signup', to: "users#new", as: "signup"
 post '/signup', to: "users#create", as: "create"
 get '/update/:id', to: "users#edit",as: "edit"
 patch '/update/:id', to: "users#update", as: "user_update"
 get '/favorites/:id', to: "users#show", as: "user"


 get '/login', to: "sessions#new", as: "login"
 post '/login', to: "sessions#create"
 get '/logout', to: "sessions#destroy"  


end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :country
  has_many :users, through: :favorite_articles
  has_many :favorite_articles

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :articles

  end

app/models/favorite_article.rb
class FavoriteArticle < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/home.rb
class Home < ActiveRecord::Base
  has_many :articles

end

app/models/read_later_article.rb
class ReadLaterArticle < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, through: :favorite_articles
  has_many :favorite_articles

  has_secure_password
  validates_presence_of :password
  validates_presence_of :password_confirmation
  validates :password, length: { minimum: 8 }, allow_nil: true

  validates :email, uniqueness: true
  validates_format_of :email,:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_presence_of :first_name
  validates_presence_of :last_name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def set_user
    @user = User.find(session[:user_id])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_user

  def new 
    @article = Article.new
  end

  def index
    @articles = Article.all
  end

  def show

  end

  private 

  def article_params
    params.require[:article].permit(:name, :url, :country_name)
  end

end

app/controllers/countries_controller.rb
require 'pry'

class CountriesController < ApplicationController

  before_action :set_user


  def index
    @countries = Country.all
  end

  def show
    params_name = params[:slug_name]

    @country = Country.find_by(slug_name: params_name)

    
    respond_to do |format|
      format.html
      format.js {render json: @country.articles}
    end
  end

  private

  def country_params
    params.require(:country).permit(:id, :name)
  end


end

app/controllers/favorite_articles_controller.rb
class FavoriteArticlesController < ApplicationController
  before_action :set_user

  def new

  end

  def create

    article = Article.find_by(url: params.first[1])
    user_id = session[:user_id]

    user = User.find(user_id)
    @favorite_article = FavoriteArticle.find_or_create_by(user_id: user_id, article_id: article.id)
    
    if @favorite_article.save
      flash[:alert]=("Favorite article saved!")
    end

  end

  def edit

  end

  def update

  end

  private

  def article_params
    params.require(:favorite_article).permit(:user_id, :article_id)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  protect_from_forgery with: :exception
  
  before_action :set_user
  
  def index
  end

  def map 

  end

end

app/controllers/read_later_articles_controller.rb
class ReadLaterArticlesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
before_action :set_user, only: [:show, :edit, :update]

  def new
  end

  def create
   @user = User.find_by(email: params[:user][:email])
     if @user && @user.authenticate(params[:user][:password])
       session[:user_id] = @user.id
       redirect_to home_path(@user)
     else
      flash[:message] = "You have entered the wrong email or password. Please try again."
      redirect_to login_path
    end
  end

  def destroy
    session.delete :user_id
    flash[:message] = "You have successfully logged out."
    redirect_to login_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user, :except => [:index, :new, :create]

  def new 
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if !@user.save
      flash[:errors] = []
      flash[:message] = "Please fix the following errors"
      @user.errors.each do |k,v|
        flash[:errors] << "#{k}: #{v}"
      end
      render :new
    else 
      session[:user_id] = @user.id
      redirect_to home_path(@user)
    end
  end

   def show 
    @user = User.find(session[:user_id])
  end

  def index 
    @users = User.find(session[:user_id])
  end

  def edit
  end

  def update 
    @user = User.find(session[:user_id])
    if !@user.update(user_params)
          flash[:errors] = []
          flash[:message] = "Please fix the following errors:"
          @user.errors.each do |k,v|
              flash[:errors] << "#{k}: #{v}"
          end
          render :edit
        else
            redirect_to @user
        end
  end

  private
  
  def set_user
    @user = User.find(session[:user_id])
  end

  def user_params
    params.require(:user).permit(:user_id, :first_name, :last_name, :email, :password, :password_confirmation)
  end

end
  

app/views/articles/index.html.erb
<%= render template: 'layouts/_navbar' %>

<h1>Get to know your world. Today.</h1>
<h3>&nbsp;&nbsp;&nbsp;&nbsp;Browse the list below for today's top articles around the world:</h3>

<ul class="list-group">

  <% @articles.each_with_index do |article, index|%>

    <li class="list-group-item">
        
        <h5>

          (<%= link_to article.country_name, country_articles_path(article.country.slug_name) %>).

          <strong id=<%= index %>>
          <%= article.title %>. <%= link_to "link", article.url, :target => "_blank", :class => "country-articles-links" %> 
          
          <%= button_tag "Add to Favorites", class: "add_to_favorites_articles btn btn-default", remote: true %>
          
          <%#= #button_tag "Save for Later", class: "save_for_later_countries btn btn-default", remote: true%>
          
          </strong>

        </h5>
    </li>
  <% end %>
</ul>

  <%= render template: "layouts/_footer" %>

 

app/views/articles/new.html.erb
Coming soon...ability to add your own article.

app/views/countries/edit.html.erb
Ability to edit a country name....coming soon.

(have to figure out how to make it match the layer name, and not have it conflict. Maybe a user specific name attribute...set it equal to the layer name if user specific attribute is blank...)

app/views/countries/index.html.erb
<%= render template: 'layouts/_navbar' %>


<!-- HOME -->
    <section class="module module-header bg-dark bg-dark-50" data-background="<%= asset_path("looking-glass.jpg") %>">

      <div class="container">

        <!-- MODULE TITLE -->
        <div class="row">

          <div class="col-sm-8 col-sm-offset-2">

            <h1 class="module-title font-alt align-center"><br><br>Today's Events Around the world</h1>
            <h3 class="module-subtitle font-inc align-center">Scroll, search, explore.

            
            </h3>

            <div class="module-subtitle font-inc align-center">
              <div class="post-meta font-inc">
              </div>
            </div>

          </div>

        </div>
        <!-- /MODULE TITLE -->

      </div>

    </section >

<!-- BLOG SINGLE -->
    <section class="module">

      <div class="container">

        <div class="row">

          <div class="col-sm-8 col-sm-offset-2">

            <!-- POST -->
            <div class="post">

              <!-- <div class="post-thumbnail">
                <a href="blog-single.html"><img src="assets/images/post-1.jpg" alt=""></a>
              </div> -->

              <div class="post-entry">

<!-- my code!!
 -->

<ol class="list-group">
<% @countries.each do |country| %>
  <li class="list-group-item">

    <h3><%= link_to country.name, country_articles_path(country.slug_name)%></h3><h5>Today's top 10 articles:
    <ul class="list-group">
      
      <br>
      <% country.articles.each do |article| %>
      <li class="list-group-item">
        <%= link_to article.title, article.url, :target => "_blank" %>. <br><%= button_tag "Add to Favorites", class: "add_to_favorites_articles btn btn-default", remote: true %>
      </li>
      <% end %>
      
    </ul>
    </h5>


  </li>
<% end %>
</ol>

</div>

            </div>

  <%= render template: "layouts/_contact_bottom" %>

app/views/countries/new.html.erb
Ability to add your own country....coming soon!

app/views/countries/show.html.erb
<%= render template: 'layouts/_navbar' %>

<!-- HOME -->
  <section id="home" class="module-hero module-parallax module-fade bg-dark-50" data-background="<%= asset_path("globe.jpg") %>">

    <div class="hs-caption container">
      <div class="caption-content">
        <div class="hs-title-size-3 font-alt m-b-20">
          <h1>Welcome to <%= @country.name %>!</h1>

        </div>
        <div class="hs-title-size-1 font-inc">
            Browse below for articles
        </div>
      </div>
    </div>

  </section >
  <!-- /HOME -->

      <!-- /HOME -->
<!-- BLOG SINGLE -->
    <section class="module">

      <div class="container">

        <div class="row">

          <div class="col-sm-8 col-sm-offset-2">

            <!-- POST -->
            <div class="post">

              <!-- <div class="post-thumbnail">
                <a href="blog-single.html"><img src="assets/images/post-1.jpg" alt=""></a>
              </div> -->

              <div class="post-entry">

<!-- my code
 -->


<ol class="list-group">

      <li class="list-group-item">
        <h5>Today's top 10 articles:</h5>
      </li>

      <br>

      <ul class="list-group">

        <% @country.articles.each_with_index do |article, index| %>
        <li class="list-group-item" id=<%= index %>>
        
          <%= link_to article.title, article.url, :target => "_blank", :class => "country-articles-links" %>. <br><%= button_tag "Add to Favorites", class: "add_to_favorites_articles btn btn-default", remote: true %>
          <%#= #button_tag "Save for Later", class: "save_for_later_countries"%>

        <!--  <input type="button" class="button" value="Add to Favorites" id="add_to_favorites_countries">
        <input type="button" class="button" value="Save for Later" id="save_for_later_countries"> -->
        </li>
        <% end %>
      
    </ul>
    </h5>

  </li>
</ol>


</div>
</div>
</div>
</div>
   <%= render template: "layouts/_footer" %>

</div>
</section>

app/views/home/index.html.erb
  <%= render template: 'layouts/_navbar' %>
 <!-- HOME -->

  <section id="home" class="module-hero module-parallax module-fade module-full-height bg-dark-30" data-background="<%= asset_path("Binoculars.jpg") %>">

    <div class="hs-caption container">
      <div class="caption-content">
        <div class="hs-title-size-4 font-alt m-b-30">
          Mapping the News 
        </div>
        <div class="hs-title-size-1 font-inc">
          It's a big world out there. <br/> Explore.
          <br><br>

          <h3 class="module-subtitle font-inc align-center"> <%= link_to "Browse List of Articles", today_path, class: "btn btn-d btn-circle" %><br> <br>
        <%= link_to "Browse Article Map", home_map_path, class: "btn btn-d btn-circle" %>

        </h3>

        </div>
      </div>
    </div>

  </section >
  <!-- /HOME --> 


    <!-- TESTIMONIAL -->
    <section class="module-small">

      <div class="container">

        <div class="row">

          <!-- MODULE TITLE -->
          <div class="col-sm-6">
            <h2 class="module-title font-alt">Mapping the News</h2>
          </div>
          <!-- /MODULE TITLE -->

          <!-- BLOCKQUOTE -->
          <div class="col-sm-6">
            <blockquote class="font-serif align-right">
              <p>Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning.</p>
              <p class="font-inc font-uppercase">- Albert Einstein </p>
              
            </blockquote>
          </div>
          <!-- /BLOCKQUOTE -->

        </div>

      </div>

    </section>
    <!-- /TESTIMONIAL -->

    <!-- ABOUT -->
    <section class="module p-t-0 p-b-0" data-background="<%= asset_path("home_newspapers.jpg") %>" >

      <div class="container-fluid">

        <div class="row relative">

          <div class="col-sm-12 col-md-6 col-md-offset-6 col-bg">

            <h2 class="module-title font-alt">About</h2>

            <div class="module-subtitle font-inc">
              Mapping the News helps its readers stay informed about world events. 
            </div>

            <p>Perhaps the Irish orator, philosopher and politician, Edmund Burke said it best with the following quotation: All that is necessary for the triumph of evil is that good men do nothing. This resonates with social advocates the world over. And there is indeed a great truth and responsibility inherent in these words.</p>

            <p>On a more practical level, the goings-on in remote places around the world do indeed have a direct bearing on economic relationships, political affiliations and global power blocs. The recent conflagration in the Ukraine set in motion a sharp divide between the US and its allies on one hand, and the Russians on the other. If the moral aspect of international crises does not resonate with everyday citizens, the economic component most certainly does.</p>

            <p>Let us help you stay informed </p>

            <!-- <ul class="social-list">
              <li><a href="#"><span><i class="fa fa-facebook"></i></span></a></li>
              <li><a href="#"><span></span><i class="icon-twitter"></i>
              </a></li>
              <li><a href="#"><span>
                <i class="fa fa-instagram"></i>
              </span></a></li>
            </ul> -->

          </div>

        </div>

      </div>

    </section>
    <!-- /ABOUT -->

  <%= render template: "layouts/_contact_bottom" %>

  <%= render template: "layouts/_footer" %>

app/views/home/map.html.erb
<html>
<head>
    <meta charset='utf-8' />
    <title></title>
    <meta name='viewport' content='initial-scale=0.5,maximum-scale=1,user-scalable=no' />
  
  <script src='https://api.mapbox.com/mapbox-gl-js/v0.19.1/mapbox-gl.js'></script> <!-- Map doesn't appear without this -->

  <link href='https://api.mapbox.com/mapbox-gl-js/v0.19.1/mapbox-gl.css' rel='stylesheet' /> <!-- styling for the bubbles -->
   
</head>

<body>

<section class="module-hero module-parallax module-fade module-full-height bg-dark-30" data-background="<%= asset_path("black.jpg") %>">

<%= render template: 'layouts/_navbar' %>


<div id='map'></div>

<section>
</body>
</html>

app/views/layouts/_contact_bottom.html.erb
    <!-- CONTACT -->
    <section class="module-small">
    
      <div class="container">
    
        <div class="row">
    
          <!-- CONTENT BOX -->
          <div class="col-sm-4">
            <div class="content-box">
              <div class="content-box-icon">
                <span class=""></span>
              </div>
              <div class="content-box-title font-inc">
                New York, USA
              </div>
            </div>
          </div>
          <!-- /CONTENT BOX -->
    
          <!-- CONTENT BOX -->
          <div class="col-sm-4">
            <div class="content-box">
              <div class="content-box-icon">
                <span class=""></span>
              </div>
              <div class="content-box-title font-inc">
                mappingthenews@gmail.com
              </div>
            </div>
          </div>
          <!-- /CONTENT BOX -->
    
          <!-- CONTENT BOX -->
          <div class="col-sm-4">
            <div class="content-box">
              <div class="content-box-icon">
                <span class=""></span>
              </div>
              <div class="content-box-title font-inc">
                @_mappingthenews
              </div>
            </div>
          </div>
          <!-- /CONTENT BOX -->
    
        </div>
    
      </div>
    
    </section>
    <!-- /CONTACT -->

app/views/layouts/_footer.html.erb
   <footer class="footer">
    
      <div class="container">
    
        <div class="row">
    
          <div class="col-sm-12 text-center">
            <p class="copyright font-inc m-b-0">2016 MappingTheNews, All Rights Reserved.</p>
          </div>
    
        </div>
    
      </div>
    
    </footer>

app/views/layouts/_home_portfolio.html.erb
 <!-- WRAPPER -->
  <div class="wrapper">

    <!-- PORTFOLIO -->
    <section class="module-small p-t-20 p-b-0 p-t-sm-0">

      <div class="container">

        <!-- PORTFOLIO FILTER -->
        <div class="row">
          <div class="col-sm-12">

            <ul id="filters" class="filter font-inc">
              <li><a href="#" data-filter="*" class="current wow fadeInUp">All</a></li>
              <li><a href="#" data-filter=".illustration" class="wow fadeInUp" data-wow-delay="0.2s">Illustration</a></li>
              <li><a href="#" data-filter=".marketing" class="wow fadeInUp" data-wow-delay="0.4s">Marketing</a></li>
              <li><a href="#" data-filter=".photography" class="wow fadeInUp" data-wow-delay="0.6s">Photography</a></li>
              <li><a href="#" data-filter=".webdesign" class="wow fadeInUp" data-wow-delay="0.8s">Web Design</a></li>
            </ul>

          </div>
        </div>
        <!-- /PORTFOLIO FILTER -->

      </div>

      <!-- PORTFOLIO LIST -->
      <ul id="works-grid" class="works-grid works-grid-masonry works-grid-3 works-hover-w">

        <!-- PORTFOLIO ITEM -->
        <li class="work-item illustration webdesign">
          <a href="portfolio-single-1.html">
            <div class="work-image">
              <%= image_tag "work-masonry-1.jpg", class: 'img-responsive', alt: ""%>
            </div>
            <div class="work-caption">
              <h3 class="work-title font-alt">Corporate Identity</h3>
              <div class="work-descr font-inc">
                Illustration
              </div>
            </div>
          </a>
        </li>
        <!-- /PORTFOLIO ITEM -->

        <!-- PORTFOLIO ITEM -->
        <li class="work-item marketing photography">
          <a href="portfolio-single-1.html">
            <div class="work-image">
              <%= image_tag "work-2.jpg", class: 'img-responsive', alt: ""%>
            </div>
            <div class="work-caption">
              <h3 class="work-title font-alt">Bag MockUp</h3>
              <div class="work-descr font-inc">
                Marketing
              </div>
            </div>
          </a>
        </li>
        <!-- /PORTFOLIO ITEM -->

        <!-- PORTFOLIO ITEM -->
        <li class="work-item illustration photography">
          <a href="portfolio-single-1.html">
            <div class="work-image">
              <%= image_tag "work-3.jpg", class: 'img-responsive', alt: ""%>
            </div>
            <div class="work-caption">
              <h3 class="work-title font-alt">Disk Cover</h3>
              <div class="work-descr font-inc">
                Illustration
              </div>
            </div>
          </a>
        </li>
        <!-- /PORTFOLIO ITEM -->

        <!-- PORTFOLIO ITEM -->
        <li class="work-item marketing photography">
          <a href="portfolio-single-1.html">
            <div class="work-image">
              <%= image_tag "work-4.jpg", class: 'img-responsive', alt: ""%>
            </div>
            <div class="work-caption">
              <h3 class="work-title font-alt">Business Card</h3>
              <div class="work-descr font-inc">
                Photography
              </div>
            </div>
          </a>
        </li>
        <!-- /PORTFOLIO ITEM -->

        <!-- PORTFOLIO ITEM -->
        <li class="work-item illustration webdesign">
          <a href="portfolio-single-1.html">
            <div class="work-image">
              <%= image_tag "work-masonry-2.jpg", class: 'img-responsive', alt: ""%>
            </div>
            <div class="work-caption">
              <h3 class="work-title font-alt">Business Cards</h3>
              <div class="work-descr font-inc">
                Webdesign
              </div>
            </div>
          </a>
        </li>
        <!-- /PORTFOLIO ITEM -->

        <!-- PORTFOLIO ITEM -->
        <li class="work-item marketing webdesign">
          <a href="portfolio-single-1.html">
            <div class="work-image">
              <%= image_tag "work-6.jpg", class: 'img-responsive', alt: ""%>
            </div>
            <div class="work-caption">
              <h3 class="work-title font-alt">Business Cards in paper clip</h3>
              <div class="work-descr font-inc">
                Marketing
              </div>
            </div>
          </a>
        </li>
        <!-- /PORTFOLIO ITEM -->

        <!-- PORTFOLIO ITEM -->
        <li class="work-item marketing webdesign">
          <a href="portfolio-single-1.html">
            <div class="work-image">
              <%= image_tag "work-7.jpg", class: 'img-responsive', alt: ""%>
            </div>
            <div class="work-caption">
              <h3 class="work-title font-alt">Business Cards in paper clip</h3>
              <div class="work-descr font-inc">
                Marketing
              </div>
            </div>
          </a>
        </li>
        <!-- /PORTFOLIO ITEM -->

      </ul>
      <!-- /PORTFOLIO LIST -->

    </section>
    <!-- /PORTFOLIO -->

  </div>
  <!-- /WRAPPER -->

app/views/layouts/_nav_bar_signup.erb
  <!-- PRELOADER -->
  <div class="page-loader">
    <div class="loader">Loading...</div>
  </div>
  <!-- /PRELOADER -->

 <nav class="navbar navbar-custom navbar-transparent navbar-fixed-top" role="navigation">

      <div class="container">
    
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#custom-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <
          <a><%= link_to "MTN", home_path, class: "navbar-brand" %></a>

        </div>
    
        <div class="collapse navbar-collapse" id="custom-collapse">
    
          <ul class="nav navbar-nav navbar-right">
    
            <li>
              <%= link_to "Home", home_path %>
            </li>
    
            <li>
            <% if @user %>
              <%= link_to "News Map", home_map_path %>
            <% else %>
              <%= link_to "News Map", login_path%>
            <% end %>
            </li>
    
            <li>
            <% if @user %>
              <%= link_to "Today's Events", today_path %>
            <% else %>
              <%= link_to "Today's Events", login_path%>
            <% end %>

            </li>
                  
            <li>
              <% if @user.id %>
                <%= link_to "My Favorites", user_path(@user)%>
              <% end %>

            </li>
    
            <li>
            <% if @user %>
              <%= link_to "LogOut", logout_path%>
            <% else %>
              <%= link_to "LogIn", login_path%>
            <% end %>
            </li>
    
          </ul>
        </div>
    
      </div>

  </nav>

app/views/layouts/_navbar.html.erb
  <!-- PRELOADER -->
  <div class="page-loader">
    <div class="loader">Loading...</div>
  </div>
  <!-- /PRELOADER -->

 <nav class="navbar navbar-custom navbar-transparent navbar-fixed-top" role="navigation">

      <div class="container">
    
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#custom-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a><%= link_to "MTN", home_path, class: "navbar-brand" %></a>

        </div>
    
        <div class="collapse navbar-collapse" id="custom-collapse">
    
          <ul class="nav navbar-nav navbar-right">
    
            <li>
              <%= link_to "Home", home_path %>
            </li>
    
            <li>
            <% if @user %>
              <%= link_to "News Map", home_map_path %>
            <% else %>
              <%= link_to "News Map", login_path%>
            <% end %>
            </li>
    
            <li>
            <% if @user %>
              <%= link_to "Today's Events", today_path %>
            <% else %>
              <%= link_to "Today's Events", login_path%>
            <% end %>

            </li>
                  
            <li>
              <% if @user %>
                <%= link_to "My Favorites", user_path(@user)%>
              <% end %>

            </li>
    
            <li>
            <% if @user %>
              <%= link_to "LogOut", logout_path%>
            <% else %>
              <%= link_to "LogIn", login_path%>
            <% end %>
            </li>
    
          </ul>
        </div>
    
      </div>

  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

<!-- From Rails -->

<title>MappingTheNews</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  
  <%= csrf_meta_tags %>

  <!-- End of Rails -->

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <%#= yield :head if content_for?(:head) %>
  
  <title>MappingTheNews</title>
  
</head>
<body>

  <!-- PRELOADER -->
  <div class="page-loader">
    <div class="loader">Loading...</div>
  </div>
  <!-- /PRELOADER -->

  <%= yield %>
 

  <!-- Scroll-up -->
  <div class="scroll-up">
    <a href="#totop"><i class="fa fa-angle-double-up"></i></a>
  </div>
  
  <!-- Javascript files -->
  <%= javascript_include_tag 'application' %>

</body>
</html>

app/views/map/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <script src="js/script.js"></script></title>
</head>
<body>


<div id="query-result">
  
</div>

</body>
</html>

app/views/users/show.html.erb
<%= render template: 'layouts/_navbar' %>

<!-- HOME -->
<section class="module module-header bg-dark bg-dark-50" data-background="<%= asset_path("globe-image.jpg") %>">

  <div class="container">

    <!-- MODULE TITLE -->
    <div class="row">

      <div class="col-sm-8 col-sm-offset-2">
        <% if @user.articles.length > 0 %>

        <h1 class="module-title font-alt align-center"><br><br><%= @user.first_name %>. Your Favorites.</h1>
        <h3 class="module-subtitle font-inc align-center"> The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.<br> - Albert Einstein

        </h3>

        <div class="module-subtitle font-inc align-center">
          <div class="post-meta font-inc">
          </div>
        </div>

        <% else %>

        <h1 class="module-title font-alt align-center"><br><br>Dear <%= @user.first_name %>, <br>You have no saved articles.</h1><h3 class="align-center">Add some!</h3><br><br>
        <h3 class="module-subtitle font-inc align-center"> <%= link_to "Browse List of Articles", today_path, class: "btn btn-d btn-circle" %><br> <br>
        <%= link_to "Browse Article Map", home_map_path, class: "btn btn-d btn-circle" %>

        </h3>

        <div class="module-subtitle font-inc align-center">
          <div class="post-meta font-inc">
          </div>
        </div>

        <% end %>


      </div>

    </div>
    <!-- /MODULE TITLE -->

  </div>

</section >

<% if @user.articles.length > 0 %>
<!-- BLOG SINGLE -->
<section class="module">

  <div class="container">

    <div class="row">

      <div class="col-sm-8 col-sm-offset-2">

        <!-- POST -->
        <div class="post">

              <!-- <div class="post-thumbnail">
                <a href="blog-single.html"><img src="assets/images/post-1.jpg" alt=""></a>
              </div> -->

              <div class="post-entry">


                <h4><div id=favorite_articles>
                  <ul class="list-group">
                    <% @user.articles.each do |article| %>
                    <li class="list-group-item">
                      (<%= link_to article.country.name, country_articles_path(article.country.slug_name) %>).
                      <%= link_to article.title, article.url %>
                    </li>
                    <% end %>
                  </ul>
                </div></h4>

<!-- <h3>Here are articles to read later:</h3>
<h4><div id=later_articles>

</div></h4>

-->
</div>
</div>
</div>
</div>
</div>
</section>
<% end %>
  <%= render template: "layouts/_contact_bottom" %>